// Short forms OSM names lack; fuzzy.ts derives initialisms. Keys are exact building names.
export const BUILDING_ALIASES: Record<string, string[]> = {
  KReSIT: ["KCDH", "Koita Centre for Digital Health", "Kanwal Rekhi", "CMINDS"],
  "Department of Bio sciences and Bio engineering": ["BSBE", "Biosciences"],
  "Department of Metalurgical and Material Science Engineering": ["MEMS", "Metallurgy"],
  "Department of Energy Sciences and Engineering": ["ESE", "DESE", "CCD", "Cafe Coffee Day"],
  Gulmohar: ["Gullu"],
  "Lecture Hall": ["LHC", "Lecture Hall Complex"],
  SOM: ["SJMSOM", "School of Management"],
  "Viktor Menezes Convention Centre": ["VMCC", "Victor Menezes Convention Centre"],
  "PC Saxena Auditorium LT": ["PCSA", "PC Saxena Auditorium"],
  "Staff Hostel Annexe": ["SHA", "Staff Hostel"],
  "Department of Chemical Engineering and Chemistry": ["ChemE"],
  "Aerospace Department": ["AE"],
  "Aerospace Engineering (Annex) + HSS": ["HSS", "Humanities", "Humanities and Social Sciences"],
  "Mathematics Department": ["Maths"],
  "Environmental Science & Engineering": ["ESED"],
  "Nandan Nilekani Main Building": ["MB"],
  SAC: ["Student Activity Centre"],
  "Society for Applied Microwave Electronics Engineering & Research": ["SAMEER"],
  "Mechanical Engineering Department": ["ME", "Mech"],
  "A91 Eco Hub": ["Economics", "A91 Economics"],
  // block codes from before OSM renamed them
  "Nilgiri (268-326)": ["B 24"],
  "Satpura (123-146)": ["B 21"],
  "Shivalik (187-240)": ["C 23"],
  "Estate Office (Central Area)": ["B-1"],
  "Computer Science & Engineering Center (New)": ["CSE"],
  "Padmavati Devi Temple": ["Devi Temple", "Padmavati Temple", "Devi Mandir"],
  "H-15 Wing B": ["H15"],
  "Lake Side Gate (Gate 1)": ["Gate 1", "Lakeside Gate", "Lake Gate"],
  "Main Gate (Gate 2)": ["Gate 2", "IITB Main Gate"],
  "Market Gate (Gate 3)": ["Gate 3", "YP Gate"],
};
